SELECT
SPTT_PK AS key,
SPTT_TEST_TYPE AS testType,
SPTT_BILLING_ITEM_CODE AS billingItemCode,
SPTT_SETUP_ITEM_CODE AS setupItemCode,
SPTT_PROCESSING_ORDER AS processingOrder,
SPTT_PROCESSING_GROUP AS processingGroup,
SPTT_SORT_ORDER AS sortOrder,
(CASE WHEN SPTT_ACTIVE_YN = 'Y' THEN 1 ELSE 0 END) AS isActive,
SPTT_COMMENT AS comments,
SPTT_PATHOGEN AS pathogen,
SPTT_ASSAY AS assay
FROM cnprcSrc_srl.SRL_PANEL_TEST_TYPES