SELECT
SSAT_PK AS key,
SSAT_SORT_ORDER AS sortOrder,
SSAT_SAMPLE AS sample,
SSAT_SAMPLE_DESC AS sampleDesc,
(CASE WHEN SSAT_ACTIVE_YN = 'Y' THEN 1 ELSE 0 END) AS isActive,
SSAT_COMMENT AS comments
FROM cnprcSrc_srl.SRL_SAMPLE_TYPES