SELECT
SSPT_PK AS key,
SSPT_SPECIES AS species,
SSPT_SPECIES_DESC AS speciesDesc,
SSPT_COMMENT AS comments,
SSPT_SORT_ORDER AS sortOrder,
(CASE WHEN SSPT_ACTIVE_YN = 'Y' THEN 1 ELSE 0 END) AS isActive
FROM cnprcSrc_srl.SRL_SPECIES_TYPES