SELECT
SUBT_PK AS key,
SUBT_ST_FK AS test,
SUBT_TYPE AS type,
(CASE WHEN SUBT_FLAG = 'Y' THEN 1 ELSE 0 END) AS flag,
SUBT_RESULTS AS results,
SUBT_RPT_DATE AS reportDate,
SUBT_TEST_DONE AS testDone,
(CASE WHEN SUBT_HIDE_ON_RPT = 'Y' THEN 1 ELSE 0 END) AS hideOnRpt,
SUBT_COMMENT AS comments,
(CASE WHEN SUBT_HIDE_COMMENT = 'Y' THEN 1 ELSE 0 END) AS hideComments
FROM cnprcSrc_srl.SRL_SUB_TESTS