language: java
dist: trusty
git:
  depth: 9999999
jdk:
  - openjdk13

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2
    - $HOME/site-library

install: skip
script:
  - wget -O ./travis.sh https://github.com/bimberlabinternal/DevOps/raw/master/travisci/travis.sh
  - bash ./travis.sh

before_deploy:
  - export RELEASE_NAME=`cat ${TRAVIS_BUILD_DIR}/release.txt`
  - 'echo "Release name: "${RELEASE_NAME}'
  - 'echo "Pull request: "${TRAVIS_PULL_REQUEST}'
  - cd $TRAVIS_BUILD_DIR

deploy:
# TODO: need to properly tag code and replace existing tag if present
# https://stackoverflow.com/questions/28217556/travis-ci-auto-tag-build-for-github-release
#  # For internal distribution
#  - provider: releases
#    api_key: ${GH_TOKEN}
#    repo: 'bimberlabinternal/BimberLabKeyModules'
#    overwrite: true
#    file_glob: true
#    file:
#      - ./lkDist/discvr/*.gz
#      - ./lkDist/prime-seq-modules/*.zip
#    name: ${RELEASE_NAME}
#    draft: false
#    body: 'This is the latest draft build, automatically published by Travis-CI.  This is not intended as a production release.'
#    skip_cleanup: true
#    tag_name: $RELEASE_NAME
#    on:
#      all_branches: true
#      #NOTE: pull requests are already skipped
#      condition: $TRAVIS_BRANCH =~ ^(develop|discvr)[0-9\.\-]*

  # For public releases
  - provider: releases
    api_key: ${GH_TOKEN}
    repo: 'BimberLab/DiscvrLabKeyModules'
    overwrite: true
    body: 'This release is compatible with LabKey Server version $TRAVIS_TAG.  It contains a full installer (which contains the core LabKey modules), and also a standalone ZIP with just the DISCVR modules.  The latter can be unzipped into your server externalModules or modules directories.'
    file_glob: true
    file:
      - ./lkDist/discvr/*.gz
      - ./lkDist/discvr_modules/*.zip
    name: ${TRAVIS_TAG}
    skip_cleanup: true
    on:
      tags: true