DROP INDEX sequenceanalysis.aa_snps_ref_aa_position_codon;
DROP INDEX sequenceanalysis.aa_snps_analysis_id;
DROP INDEX sequenceanalysis.aa_snps_ref_nt_id;
DROP INDEX sequenceanalysis.aa_snps_alignment_id;

DROP INDEX sequenceanalysis.alignment_summary_analysis_id;

DROP INDEX sequenceanalysis.IDX_alignment_summary_junction_ref_nt_id_status_alignment_id;

DROP INDEX sequenceanalysis.sequence_coverage_ref_nt_id;
