SELECT
RRI_ITEM_CODE AS itemCode,
RRI_ALT_ITEM_CODE AS altItemCode,
RRI_DESCR AS description,
RRI_CATEGORY AS category,
RRI_BASIC_COMPOSITE_TYPE AS basicCompositeType,
RRI_BASIC_RATE AS basicRate,
RRI_BASIC_UOM AS basicUOM,
RRI_BASIC_COST_CODE AS basicCostCode,
RESOURCE_RATE_ITEM_PK AS resourceRateItemPk,
RRI_TIERED_RATE_LABOR_TYPE AS tieredRateLaborType,
RRI_RATE_TIER_CODE_FK AS rateTierCodeFk,
RRI_RATE_REPORT_GROUP AS rateReportGroup,
(CASE WHEN RRI_BASIC_ITEM_LABOR_YN = 'Y' THEN 1 ELSE 0 END) AS isBasicItemLabor,
OBJECTID AS objectid,
DATE_TIME
FROM cnprcSrc_billing.ZRESOURCE_RATE_ITEM;