SELECT
RC_CODE AS code,
RC_ALT_CODE AS altCode,
RC_TITLE AS title,
(CASE WHEN RC_ANIMAL_CARE_YN = 'Y' THEN 1 ELSE 0 END) AS isAnimalCare,
(CASE WHEN RC_ACTIVE_YN = 'Y' THEN 1 ELSE 0 END) AS isActive,
OBJECTID AS objectid,
DATE_TIME
FROM cnprcSrc_billing.ZRESOURCE_CENTER;