SELECT
CWOF_ID AS templateId,
CWOF_SERVICE_TYPE AS serviceType,
CWOF_PR_CODE AS prCode,
CWOF_CHARGE_ID AS chargeId,
CWOF_BEGIN_DATE AS beginDate,
CWOF_END_DATE AS endDate,
CWOF_SUBMITTED_TIMESTAMP AS submittedOn,
CWOF_WRITTEN_TIMESTAMP AS writtenOn,
CWOF_MODIFIED_TIMESTAMP AS modifiedOn,
CWOF_COPIED_TIMESTAMP AS copiedOn,
CWOF_COPIED_WO_NO AS copiedWorkOrderNumber,
CWOF_PRINT_FLAG AS printFlag,
CWOF_INVESTIGATOR AS investigator,
CWOF_REQUESTOR AS requestor,
CWOF_DESCR AS description,
((CASE WHEN CWOF_TO_1 IS NOT NULL THEN CONCAT(CWOF_TO_1, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TO_2 IS NOT NULL THEN CONCAT(CWOF_TO_2, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TO_3 IS NOT NULL THEN CONCAT(CWOF_TO_3, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TO_4 IS NOT NULL THEN CONCAT(CWOF_TO_4, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TO_5 IS NOT NULL THEN CONCAT(CWOF_TO_5, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TO_6 IS NOT NULL THEN CONCAT(CWOF_TO_6, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TO_7 IS NOT NULL THEN CONCAT(CWOF_TO_7, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TO_8 IS NOT NULL THEN CONCAT(CWOF_TO_8, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TO_9 IS NOT NULL THEN CONCAT(CWOF_TO_9, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TO_10 IS NOT NULL THEN CONCAT(CWOF_TO_10, '//') ELSE '' END)) AS templateTo,
((CASE WHEN CWOF_CC_1 IS NOT NULL THEN CONCAT(CWOF_CC_1, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_CC_2 IS NOT NULL THEN CONCAT(CWOF_CC_2, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_CC_3 IS NOT NULL THEN CONCAT(CWOF_CC_3, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_CC_4 IS NOT NULL THEN CONCAT(CWOF_CC_4, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_CC_5 IS NOT NULL THEN CONCAT(CWOF_CC_5, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_CC_6 IS NOT NULL THEN CONCAT(CWOF_CC_6, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_CC_7 IS NOT NULL THEN CONCAT(CWOF_CC_7, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_CC_8 IS NOT NULL THEN CONCAT(CWOF_CC_8, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_CC_9 IS NOT NULL THEN CONCAT(CWOF_CC_9, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_CC_10 IS NOT NULL THEN CONCAT(CWOF_CC_10, '//') ELSE '' END)) AS templateCC,
((CASE WHEN CWOF_TEXT_1 IS NOT NULL THEN CONCAT(CWOF_TEXT_1, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_2 IS NOT NULL THEN CONCAT(CWOF_TEXT_2, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_3 IS NOT NULL THEN CONCAT(CWOF_TEXT_3, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_4 IS NOT NULL THEN CONCAT(CWOF_TEXT_4, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_5 IS NOT NULL THEN CONCAT(CWOF_TEXT_5, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_6 IS NOT NULL THEN CONCAT(CWOF_TEXT_6, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_7 IS NOT NULL THEN CONCAT(CWOF_TEXT_7, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_8 IS NOT NULL THEN CONCAT(CWOF_TEXT_8, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_9 IS NOT NULL THEN CONCAT(CWOF_TEXT_9, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_10 IS NOT NULL THEN CONCAT(CWOF_TEXT_10, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_11 IS NOT NULL THEN CONCAT(CWOF_TEXT_11, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_12 IS NOT NULL THEN CONCAT(CWOF_TEXT_12, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_13 IS NOT NULL THEN CONCAT(CWOF_TEXT_13, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_14 IS NOT NULL THEN CONCAT(CWOF_TEXT_14, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_15 IS NOT NULL THEN CONCAT(CWOF_TEXT_15, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_16 IS NOT NULL THEN CONCAT(CWOF_TEXT_16, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_17 IS NOT NULL THEN CONCAT(CWOF_TEXT_17, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_18 IS NOT NULL THEN CONCAT(CWOF_TEXT_18, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_19 IS NOT NULL THEN CONCAT(CWOF_TEXT_19, '//') ELSE '' END) ||''||
(CASE WHEN CWOF_TEXT_20 IS NOT NULL THEN CONCAT(CWOF_TEXT_20, '//') ELSE '' END)) AS templateText,
CWOF_RC_CODE AS rcCode,
CWOF_SERVICE_CODE AS serviceCode,
OBJECTID AS objectid,
DATE_TIME
FROM cnprcSrc_billing.ZCWOS_FORMAT;
