SELECT
CWO_NO AS workOrderNumber,
CWO_COMPLETION_STATUS AS completionStatus,
CWO_PERIOD_ENDING_DATE AS periodEndingDate,
CWO_SERVICE_TYPE AS serviceType,
CWO_PR_CODE AS projectCode,
CWO_CHARGE_ID AS chargeId,
CWO_ACCT_ID AS accountId,
CWO_ACCT_FUND_TYPE AS accountFundType,
CWO_COPIED_FORMAT_ID AS copiedFormatId,
CWO_BEGIN_DATE AS beginDate,
CWO_END_DATE AS endDate,
CWO_FINISH_DATE AS finishDate,
CWO_SUBMITTED_TIMESTAMP AS submittedOn,
CWO_WRITTEN_TIMESTAMP AS writtenOn,
CWO_PRINTED_TIMESTAMP AS printedOn,
CWO_MODIFIED_TIMESTAMP AS modifiedOn,
CWO_CLOSED_TIMESTAMP AS closedOn,
CWO_INVESTIGATOR AS investigator,
CWO_REQUESTOR AS requestor,
CWO_DESCR AS description,
CWO_PRINT_FLAG AS printFlag,
CWO_PRINT_VERSION_TALLY AS printVersionTally,
CWO_PRINT_PAGES_TALLY AS printPagesTally,
CWO_EX_PR_FLAG AS exPrFlag,
CWO_EX_CHARGE_FLAG AS exChargeFlag,
CWO_EX_PR_CHARGE_FLAG AS exPrChargeFlag,
CWO_EX_FUND_SERVICE_FLAG AS exFundServiceFlag,
CWO_TOTAL_CHARGE_AMT AS totalChargeAmount,
CWO_TOTAL_EXEMPT_AMT AS totalExemptAmount,
((CASE WHEN CWO_TEXT_1 IS NOT NULL THEN CONCAT(CWO_TEXT_1, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_2 IS NOT NULL THEN CONCAT(CWO_TEXT_2, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_3 IS NOT NULL THEN CONCAT(CWO_TEXT_3, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_4 IS NOT NULL THEN CONCAT(CWO_TEXT_4, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_5 IS NOT NULL THEN CONCAT(CWO_TEXT_5, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_6 IS NOT NULL THEN CONCAT(CWO_TEXT_6, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_7 IS NOT NULL THEN CONCAT(CWO_TEXT_7, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_8 IS NOT NULL THEN CONCAT(CWO_TEXT_8, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_9 IS NOT NULL THEN CONCAT(CWO_TEXT_9, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_10 IS NOT NULL THEN CONCAT(CWO_TEXT_10, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_11 IS NOT NULL THEN CONCAT(CWO_TEXT_11, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_12 IS NOT NULL THEN CONCAT(CWO_TEXT_12, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_13 IS NOT NULL THEN CONCAT(CWO_TEXT_13, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_14 IS NOT NULL THEN CONCAT(CWO_TEXT_14, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_15 IS NOT NULL THEN CONCAT(CWO_TEXT_15, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_16 IS NOT NULL THEN CONCAT(CWO_TEXT_16, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_17 IS NOT NULL THEN CONCAT(CWO_TEXT_17, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_18 IS NOT NULL THEN CONCAT(CWO_TEXT_18, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_19 IS NOT NULL THEN CONCAT(CWO_TEXT_19, '//') ELSE '' END) ||''||
(CASE WHEN CWO_TEXT_20 IS NOT NULL THEN CONCAT(CWO_TEXT_20, '//') ELSE '' END)) AS workOrderText,
CWO_SERVICE_CODE AS serviceCode,
CWO_CLIENT_PO_NUMBER AS clientPONumber,
CWO_CREDIT_COMMENT AS creditComment,
CWO_CREDIT_WORKORDER_YN AS creditWorkOrder,
CWO_CREDIT_PRIOR_WO_NO AS creditPriorWorkOrderNumber,
CWO_CREDIT_PRIOR_INVOICE_NO AS creditPriorInvoiceNumber,
OBJECTID AS objectid,
DATE_TIME
FROM cnprcSrc_billing.ZCWOS_WO
WHERE CWO_BEGIN_DATE IS NULL OR CWO_BEGIN_DATE > to_date('01-01-1900', 'DD-MM-YYYY');
