SELECT
CP_LAST_NAME AS LastName,
CP_FIRST_NAME AS FirstName,
CP_PK AS EmployeeId,
CP_POSITION AS Title,
CP_PHONE1 AS OfficePhone,
CP_EMAIL1 AS Email,
(CASE WHEN CP_STATUS = 'ACTIVE' THEN NULL ELSE CP_AUD_TIME END) AS EndDate,
CP_MIDDLE_NAME AS middleName,
CP_UNITFK AS Unit,
CP_SUPERVISOR AS Supervisor,
CP_CELL_PHONE AS CellPhone,
CP_WORK_LOCATION AS Location
FROM
cnprcSrc_complianceAndTraining.ZCRPRC_PERSON;