SELECT
CP_EMPLOYEE_ID AS employeeId,
CP_PK AS person_cnprc_pk,
CP_STATUS AS status,
(CASE
   WHEN CP_EMP_STUD='S' THEN 'STAFF'
   WHEN CP_EMP_STUD='G' THEN 'GRADUATE'
   WHEN CP_EMP_STUD='P' THEN 'POST DOC'
   WHEN CP_EMP_STUD='F' THEN 'FACULTY'
   WHEN CP_EMP_STUD='U' THEN 'UNDERGRAD'
   WHEN CP_EMP_STUD='O' THEN 'OTHER'
 END) AS emp_stud,
CP_PAGER AS pager,
CP_DEPARTFK AS departfk,
CP_INSTITUTION AS institution,
CP_SPONSOR AS sponsor,
CP_COMMENT AS comments
FROM
cnprcSrc_complianceAndTraining.ZCRPRC_PERSON;