update.packages(checkBuilt=TRUE, ask=FALSE)
install.packages('plyr', dependencies=TRUE, repos='http://cran.rstudio.com')
install.packages('perm', dependencies=TRUE, repos='http://cran.rstudio.com')
install.packages('reshape', dependencies=TRUE, repos='http://cran.rstudio.com')
install.packages('reshape2', dependencies=TRUE, repos='http://cran.rstudio.com')
install.packages('gridExtra', dependencies=TRUE, repos='http://cran.rstudio.com')
install.packages('ggplot2', dependencies=TRUE, repos='http://cran.rstudio.com')
install.packages('data.table', dependencies=TRUE, repos='http://cran.rstudio.com')