name: Build DISCVR
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    tags-ignore:
      - latest
  pull_request:
jobs:
  build-modules:
    # See: https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context
    # https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables
    if: github.repository == 'BimberLab/DiscvrLabKeyModules'
    runs-on: ubuntu-latest
    steps:
      - name: "Find default branch"
        uses: octokit/request-action@v2.x
        id: get_default_branch
        with:
          route: GET /repos/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: "Print default branch"
        run: |
          DEFAULT_BRANCH='${{ fromJson(steps.get_default_branch.outputs.data).default_branch }}'
          echo 'Default branch: '$DEFAULT_BRANCH
          echo ::set-output name=branch::"$DEFAULT_BRANCH"
        id: default-branch

      - name: Extract branch name
        shell: bash
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          echo 'Current branch: '$BRANCH
          echo ::set-output name=branch::"$BRANCH"
        id: extract-branch

      - name: "Debug"
        run: |
          echo 'github.ref_name: ${{ github.ref_name }}'
          echo 'github.ref: ${{ github.ref }}'
          echo 'event_name: ${{ github.event_name }}'
          echo 'base_ref: ${{ github.base_ref }}'
          echo 'extract-branch: ${{ steps.extract-branch.branch }}'
          echo 'default-branch: ${{ steps.default-branch.branch }}'
        id: debug

      - name: "Build DISCVR"
        uses: bimberlabinternal/DevOps/githubActions/discvr-build@master
        with:
          artifactory_user: ${{secrets.artifactory_user}}
          artifactory_password: ${{secrets.artifactory_password}}
          # NOTE: permissions are limited on the default secrets.GITHUB_TOKEN, including updating workflows, so use a personal access token
          github_token: ${{ secrets.PAT }}
        env:
          # Only generate the distribution if this is the default branch
          GENERATE_DIST: ${{ steps.default-branch.branch == github.ref_name && '1' || '0' }}

      - name: Publish Release
        if: ${{ steps.default-branch.branch == github.ref_name && github.event_name == 'push' && github.base_ref == '' }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.PAT }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build: ${{ fromJson(steps.get_default_branch.outputs.data).default_branch }}"
          files: /home/runner/work/_temp/_github_home/lkDist/discvr/DISCVR-*