name: Build DISCVR
on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'
jobs:
  build-modules:
    # See: https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context
    # https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables
    if: github.repository == 'BimberLab/DiscvrLabKeyModules'
    runs-on: ubuntu-latest
    steps:
      - name: "Build DISCVR"
        uses: bimberlabinternal/DevOps/githubActions/discvr-build@master
        with:
          artifactory_user: ${{secrets.artifactory_user}}
          artifactory_password: ${{secrets.artifactory_password}}
          # NOTE: permissions are limited on the default secrets.GITHUB_TOKEN, including updating workflows, so use a personal access token
          github_token: ${{ secrets.PAT }}

