name: Build DISCVR
on:
  workflow_dispatch:
  push:
    branches:
      - !latest
  pull_request:
jobs:
  build-modules:
    # See: https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context
    # https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables
    if: github.repository == 'BimberLab/DiscvrLabKeyModules'
    runs-on: ubuntu-latest
    steps:
      - name: "Build DISCVR"
        uses: bimberlabinternal/DevOps/githubActions/discvr-build@master
        with:
          artifactory_user: ${{secrets.artifactory_user}}
          artifactory_password: ${{secrets.artifactory_password}}
          # NOTE: permissions are limited on the default secrets.GITHUB_TOKEN, including updating workflows, so use a personal access token
          github_token: ${{ secrets.PAT }}

      - name: Publish Release

        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.PAT }}"
          prerelease: true
          title: "Release "
          files: |
            /home/runner/work/_temp/_github_home/lkDist/discvr/DISCVR-*
