name: Publish Release
on:
  release:
    types: [created]
jobs:
  generate:
    name: Create release-artifacts
    # See: https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context
    # https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables
    # Note: 'latest' is a tag created by branch_latest.yml, which is the latest development build. This should not trigger normal releases.
    if: github.repository == 'BimberLab/DiscvrLabKeyModules' && github.ref != 'refs/tags/latest'
    runs-on: ubuntu-latest
    steps:
      - name: "Build DISCVR"
        uses: bimberlabinternal/DevOps/githubActions/discvr-build@master
        with:
          artifactory_user: ${{secrets.artifactory_user}}
          artifactory_password: ${{secrets.artifactory_password}}
          # NOTE: permissions are limited on the default secrets.GITHUB_TOKEN, including updating workflows, so use a personal access token
          github_token: ${{ secrets.PAT }}
        env:
          GENERATE_DIST: 1

      - name: Upload Artifacts
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: /home/runner/work/_temp/_github_home/lkDist/discvr/DISCVR-*
